# Generated by Django 3.2.7 on 2021-09-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
